<?xml version="1.0" encoding="utf-8"?><Database Name="QLBANSACH" Class="DataBookDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-42EV1F8L\MSSQLSERVER_NHAN;Initial Catalog=QLBANSACH;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLBANSACHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETDATHANG" Member="CHITIETDATHANGs">
    <Type Name="CHITIETDATHANG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoDH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDATHANG" Member="DONDATHANG" ThisKey="SoDH" OtherKey="SoDH" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="SACH_CHITIETDATHANG" Member="SACH" ThisKey="MaSach" OtherKey="MaSach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIETSACH" Member="VIETSACHes">
    <Type Name="VIETSACH">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ViTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SACH_VIETSACH" Member="SACH" ThisKey="MaSach" OtherKey="MaSach" Type="SACH" IsForeignKey="true" />
      <Association Name="TACGIA_VIETSACH" Member="TACGIA" ThisKey="MaTG" OtherKey="MaTG" Type="TACGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETKM" Member="CHITIETKMs">
    <Type Name="CHITIETKM">
      <Column Name="ID_KM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SACH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KHUYENMAI_CHITIETKM" Member="KHUYENMAI" ThisKey="ID_KM" OtherKey="ID" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="SACH_CHITIETKM" Member="SACH" ThisKey="ID_SACH" OtherKey="MaSach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUDE" Member="CHUDEs">
    <Type Name="CHUDE">
      <Column Name="MaCD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CHUDE_SACH" Member="SACHes" ThisKey="MaCD" OtherKey="MaCD" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.CTPHIEUNHAPSACH" Member="CTPHIEUNHAPSACHes">
    <Type Name="CTPHIEUNHAPSACH">
      <Column Name="PHIEUNHAPSACH_ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SACH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGTHUCNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA_CTNHAPSACH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TINHTRANG_CTPHIEUNHAPSACH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LYDO_CTPHIEUNHAPSACH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GHICHU_CTIETPHIEUNHAPSACH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFILEDBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MODIFILEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PHIEUNHAPSACH_CTPHIEUNHAPSACH" Member="PHIEUNHAPSACH" ThisKey="PHIEUNHAPSACH_ID" OtherKey="PHIEUNHAPSACH_ID" Type="PHIEUNHAPSACH" IsForeignKey="true" />
      <Association Name="SACH_CTPHIEUNHAPSACH" Member="SACH" ThisKey="ID_SACH" OtherKey="MaSach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="SoDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_TAIKHOAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HinhThucThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="THANHTIEN_HOADON" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFILEDBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MODIFILEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHICHU_HOADON" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDATHANG" Member="CHITIETDATHANGs" ThisKey="SoDH" OtherKey="SoDH" Type="CHITIETDATHANG" />
      <Association Name="TAIKHOAN_DONDATHANG" Member="TAIKHOAN" ThisKey="ID_TAIKHOAN" OtherKey="ID" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayBD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayKT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sale" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="KHUYENMAI_CHITIETKM" Member="CHITIETKMs" ThisKey="ID" OtherKey="ID_KM" Type="CHITIETKM" />
    </Type>
  </Table>
  <Table Name="dbo.LIENHE" Member="LIENHEs">
    <Type Name="LIENHE">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CONTENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITAIKHOAN" Member="LOAITAIKHOANs">
    <Type Name="LOAITAIKHOAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChiTietquyen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GHICHU_LOAITAIKHOAN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFILEDBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MODIFILEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LOAITAIKHOAN_TAIKHOAN" Member="TAIKHOANs" ThisKey="ID" OtherKey="ID_LOAITK" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.NHAXUATBAN" Member="NHAXUATBANs">
    <Type Name="NHAXUATBAN">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="NHAXUATBAN_PHIEUNHAPSACH" Member="PHIEUNHAPSACHes" ThisKey="MaNXB" OtherKey="NXB_ID" Type="PHIEUNHAPSACH" />
      <Association Name="NHAXUATBAN_SACH" Member="SACHes" ThisKey="MaNXB" OtherKey="MaNXB" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAPSACH" Member="PHIEUNHAPSACHes">
    <Type Name="PHIEUNHAPSACH">
      <Column Name="PHIEUNHAPSACH_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NXB_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TENPHIEUNHAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GHICHU_NHAPSACH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFILEDBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MODIFILEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PHIEUNHAPSACH_CTPHIEUNHAPSACH" Member="CTPHIEUNHAPSACHes" ThisKey="PHIEUNHAPSACH_ID" OtherKey="PHIEUNHAPSACH_ID" Type="CTPHIEUNHAPSACH" />
      <Association Name="NHAXUATBAN_PHIEUNHAPSACH" Member="NHAXUATBAN" ThisKey="NXB_ID" OtherKey="MaNXB" Type="NHAXUATBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RATING" Member="RATINGs">
    <Type Name="RATING">
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SACH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Star" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SACH_RATING" Member="SACH" ThisKey="ID_SACH" OtherKey="MaSach" Type="SACH" IsForeignKey="true" />
      <Association Name="TAIKHOAN_RATING" Member="TAIKHOAN" ThisKey="IDUser" OtherKey="ID" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GiaBia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Weight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SACH_CHITIETDATHANG" Member="CHITIETDATHANGs" ThisKey="MaSach" OtherKey="MaSach" Type="CHITIETDATHANG" />
      <Association Name="SACH_VIETSACH" Member="VIETSACHes" ThisKey="MaSach" OtherKey="MaSach" Type="VIETSACH" />
      <Association Name="SACH_CHITIETKM" Member="CHITIETKMs" ThisKey="MaSach" OtherKey="ID_SACH" Type="CHITIETKM" />
      <Association Name="SACH_CTPHIEUNHAPSACH" Member="CTPHIEUNHAPSACHes" ThisKey="MaSach" OtherKey="ID_SACH" Type="CTPHIEUNHAPSACH" />
      <Association Name="SACH_RATING" Member="RATINGs" ThisKey="MaSach" OtherKey="ID_SACH" Type="RATING" />
      <Association Name="CHUDE_SACH" Member="CHUDE" ThisKey="MaCD" OtherKey="MaCD" Type="CHUDE" IsForeignKey="true" />
      <Association Name="NHAXUATBAN_SACH" Member="NHAXUATBAN" ThisKey="MaNXB" OtherKey="MaNXB" Type="NHAXUATBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SLIDE" Member="SLIDEs">
    <Type Name="SLIDE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IMAGE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LINK" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="from_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="to_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TieuSu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="TACGIA_VIETSACH" Member="VIETSACHes" ThisKey="MaTG" OtherKey="MaTG" Type="VIETSACH" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAITK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL_TK" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI_TK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="GHICHU_TK" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFILEDBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MODIFILEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TAIKHOAN_DONDATHANG" Member="DONDATHANGs" ThisKey="ID" OtherKey="ID_TAIKHOAN" Type="DONDATHANG" />
      <Association Name="TAIKHOAN_RATING" Member="RATINGs" ThisKey="ID" OtherKey="IDUser" Type="RATING" />
      <Association Name="LOAITAIKHOAN_TAIKHOAN" Member="LOAITAIKHOAN" ThisKey="ID_LOAITK" OtherKey="ID" Type="LOAITAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>